name: Security check
on: [push]
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bandit
        uses: pyCA/bandit-action@v1.9.4
        with:
          args: "src/ -ll"
